hub:
  cookieSecret: "dd9662c06de44e059ae6ba092e23416651ffaf1f1d5c89f063ba7fd8c888939b"
  db:
    type: sqlite-memory
proxy:
  secretToken: "27da322913806d312e8ca91be1af9c130099895e69502926194be0f5447fcb27"
  https:
    enabled: true
    hosts:
      - ugba199-fall-2021.haastech.org
    letsencrypt:
      contactEmail: tony_cricelli@berkeley.edu
  service:
    loadBalancerIP: 34.68.187.65
#cull:
#  enabled: true
#  users: false
#  timeout: 3600
#  every: 600
#prePuller:
#  enabled: false
singleuser:
  image:
    pullPolicy: IfNotPresent
    name: montereytony/mba200a
    tag: jup2-2-12
#    name: montereytony/ugba199
#    tag: jup2-6
#    name: montereytony/ugba199
#    tag: jup2-4
#    name: montereytony/ugba199-fall-2021
#    tag: local10
#    tag: local9
#    tag: local8
#    tag: local7
#    tag: local5
#    tag: local4
#    tag: local3
#    tag: local2
#    tag: local1
#    name: montereytony/ugba147
#    tag: ugba88-Spring-2021-17
#    pullPolicy: IfNotPresent
#    name: montereytony/ugba147
#    tag: ugba88-Spring-2021-19
#    tag: ugba199-Spring-2021-17
#    tag: ugba199-Spring-2021-13
#    tag: ugba199-Spring-2021-12
  memory:
    limit: 6G
    guarantee: 6G
  cpu:
    limit: 2
    guarantee: 1
  storage:
    capacity: 10Gi
    dynamic:
      storageClass: standard
    extraVolumes:
      - name: jupyterhub-shared
        persistentVolumeClaim:
          claimName: nfs-pv-ugba199-fall
    extraVolumeMounts:
      - name: jupyterhub-shared
        mountPath: /home/jovyan/shared
  lifecycleHooks:
    postStart:
      exec:
        command: ["/bin/sh", "-c", "/tmp/add_files.sh;mkdir -p my-work"]
auth:
  type: google
  google:
    clientId: "152813298217-1e7ap4ie9rugg5mfh2nmenc3f7d9o55g.apps.googleusercontent.com"
    clientSecret: "jXNHCWRcYWfXW1Y9HV0zhUuZ"
    callbackUrl: "https://ugba199-fall-2021.haastech.org/hub/oauth_callback"
    hostedDomain: [berkeley.edu]
    loginService: "your Berkeley Account."
  admin:
    users:
      - tony_cricelli
      - rhuntsinger
      - asantillan
  whitelist:
    users:
      - ishika.goel
      - jacobschillen
      - anniedabo
      - gaowenhuang
      - rongsen_li
      - cylaura
      - ashna.wadhwa
      - j_wilson5487
      - wtsai869
      - zevlyn
      - jianingyu
