apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: fanout-ingress
spec:
  rules:
  - http:
      paths:
      - path: /mfe230t-1/*
        backend:
          serviceName: proxy-public
          servicePort: 80
