hub:
  cookieSecret: "7e887dd5c5b9d9cd51d98ea1b42014bea23b9bf258b7b5cf080509403f3a921d"
  db:
    type: sqlite-memory
proxy:
  secretToken: "9c082a87132bc584c4d2c183a2b415d5543e74fbb7a9fbc8c4c53e305deb7297"
  https:
    enabled: true
    hosts:
      - ewmba290t-12.haastech.org
    letsencrypt:
      contactEmail: tony_cricelli@berkeley.edu
  service:
    loadBalancerIP: 35.225.105.35
prePuller:
  enabled: false
singleuser:
  image:
     name: montereytony/sql101
     tag: latest
  memory:
    limit: 2G
    guarantee: .5G
  cpu:
    limit: 1
    guarantee: .5
  storage:
    capacity: 5Gi
    dynamic:
      storageClass: standard
#      storageClass: jupyterhub-user-ssd
  lifecycleHooks:
    postStart:
      exec:
        command:
          - "sh"
          - "-c"
          - >
            mkdir -p my-work
#            gitpuller https://github.com/rahuntsinger/ugba147test main shared
auth:
  type: google
  google:
    clientId: "152813298217-1e7ap4ie9rugg5mfh2nmenc3f7d9o55g.apps.googleusercontent.com"
    clientSecret: "jXNHCWRcYWfXW1Y9HV0zhUuZ"
    callbackUrl: "https://ewmba290t-12.haastech.org/hub/oauth_callback"
    hostedDomain: [berkeley.edu]
    loginService: "your Berkeley Account."
