hub:
  cookieSecret: "c3fc3539a6a14198490be2f51c516402e65b7e9b697bc611d09894fb909c2b62"
  db:
    type: sqlite-memory
proxy:
  secretToken: "a8710344ae4f5af51bf85b5218708d8deb437d62e0464b684b40d799bf74ab34"
prePuller:
  enabled: true
singleuser:
  image:
    name: montereytony/ugba147
    tag: ugba147-Spring-2021-7
  memory:
    limit: 2G
    guarantee: 2G
  cpu:
    limit: 1
    guarantee: 1
  storage:
    capacity: 1Gi
    dynamic:
      storageClass: standard
  lifecycleHooks:
    postStart:
      exec:
        command:
          - "sh"
          - "-c"
          - >
            mkdir -p my-work;
auth:
  type: google
  google:
    clientId: "152813298217-1e7ap4ie9rugg5mfh2nmenc3f7d9o55g.apps.googleusercontent.com"
    clientSecret: "jXNHCWRcYWfXW1Y9HV0zhUuZ"
    callbackUrl: "https://ewmba263-11-spring-2022.haastech.org/hub/oauth_callback"
    hostedDomain: [berkeley.edu]
    loginService: "your Berkeley Account."
  admin:
    users:
      - tony_cricelli
      - olivia.natan
