apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pv-ewmba263-11-spring-2022
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
