apiVersion: v1
kind: PersistentVolume
metadata:
  name: xzhang-pv-volume
spec:
  capacity: 
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/jhub/2020/xzhang/mysql/master
