#https://www.linuxtechi.com/configure-nfs-persistent-volume-kubernetes/
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-ugba147-2021-summer2
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: nfs
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /home/ugba147/ugba147-2021-summer
    server: 10.128.0.10
