apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pv-ugba147-2021-summer-home
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
