#https://www.linuxtechi.com/configure-nfs-persistent-volume-kubernetes/
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-ewmba217
spec:
  capacity:
    storage: 30Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: nfs
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /home/ewmba217/shared
    server: 10.128.0.10
