hub:
  cookieSecret: "819eb1873a3077550ba77b28b843eaccd55788f945ab8e84766a62116478071d"
  db:
    type: sqlite-memory
proxy:
  secretToken: "09283d45f600a5fd26916ec234097a7a4b46b7ac3f8b251a77604717316c0c4a"
#  service:
#    type: ClusterIP
prePuller:
  enabled: false
singleuser:
  image:
    name: montereytony/jupyterdesktop
    tag: test10
  memory:
    limit: 2G
    guarantee: 2G
  cpu:
    limit: 1
    guarantee: 1
  storage:
    capacity: 1Gi
    dynamic:
      storageClass: standard
#      storageClass: jupyterhub-user-ssd
  lifecycleHooks:
    postStart:
      exec:
        command:
          - "sh"
          - "-c"
          - >
            mkdir -p my-work;
auth:
  type: google
  google:
    clientId: "152813298217-1e7ap4ie9rugg5mfh2nmenc3f7d9o55g.apps.googleusercontent.com"
    clientSecret: "jXNHCWRcYWfXW1Y9HV0zhUuZ"
    callbackUrl: "https://devp229-fall-2021.haastech.org/hub/oauth_callback"
    hostedDomain: [berkeley.edu]
    loginService: "your Berkeley Account."
#
#
#
  admin:
    users:
      - tony_cricelli
      - nperales
