kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: data-xzhang-mysql-mariadb-master-0
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
