hub:
  cookieSecret: "67c32cb579bd7e04110e96184f606733be208bb8a39d480f83ef53ca644c1485"
  db:
    type: sqlite-memory
proxy:
  secretToken: "3c1edfbc7dc37cf510adc80feda35d4df066d8b33c5aa0f9a06349ce38bb2b5d"
#  service:
#    type: ClusterIP
prePuller:
  enabled: false
singleuser:
  image:
     name: montereytony/sql101
     tag: latest
  memory:
     limit: 6G
     guarantee: 1G
  cpu:
    limit: 2
    guarantee: 1
  storage:
    capacity: 5Gi
    dynamic:
      storageClass: standard
#      storageClass: jupyterhub-user-ssd
  lifecycleHooks:
    postStart:
      exec:
        command:
          - "sh"
          - "-c"
          - >
            mkdir -p my-work
#            /opt/conda/bin/gitpuller https://github.com/rahuntsinger/ugba147test main shared;
auth:
  type: google
  google:
    clientId: "152813298217-1e7ap4ie9rugg5mfh2nmenc3f7d9o55g.apps.googleusercontent.com"
    clientSecret: "jXNHCWRcYWfXW1Y9HV0zhUuZ"
    callbackUrl: "https://mba290t-12.haastech.org/hub/oauth_callback"
    hostedDomain: [berkeley.edu]
    loginService: "your Berkeley Account."
