hub:
  cookieSecret: "8f935c7a7d614feaa5a48a277766a5b9849cc57a8f0ae0c8740d5b34344b2874"
  db:
    type: sqlite-memory
proxy:
  secretToken: "846f78dbf8e3c9445676f5a5acf84c4ab3ac43f352ad0bdacd034210a1282e0c"
#  https:
#    enabled: true
#    type: offload
#  service:
#    type: ClusterIP
#    loadBalancerIP: 10.128.0.59
prePuller:
  enabled: false
singleuser:
  image:
    name: montereytony/mba263
    tag: 103042
  memory:
    limit: 6G
    guarantee: 1G
  cpu:
    limit: 2
    guarantee: 1
  storage:
    capacity: 5Gi
    dynamic:
      storageClass: standard
#      storageClass: jupyterhub-user-ssd
  lifecycleHooks:
    postStart:
      exec:
        command:
          - "sh"
          - "-c"
          - >
            mkdir -p my-work;
#            /opt/conda/bin/gitpuller https://github.com/rahuntsinger/ugba147test main shared;
auth:
  type: google
  google:
    clientId: "152813298217-1e7ap4ie9rugg5mfh2nmenc3f7d9o55g.apps.googleusercontent.com"
    clientSecret: "jXNHCWRcYWfXW1Y9HV0zhUuZ"
    callbackUrl: "https://mba217.haastech.org/hub/oauth_callback"
    hostedDomain: [berkeley.edu]
    loginService: "your Berkeley Account."
