hub:
  cookieSecret: "d1ddd59e213d5dd9b969c67f6abc5870f5010a81ea750c3903a3c62aca998657"
  db:
    type: sqlite-memory
proxy:
  secretToken: "e99ced63df7fc9c30b8b437f99d4a9d420ca9c3812993d7031307e7170ab92ce"
  https:
    enabled: true
    hosts:
      - ugba88.haastech.org
    letsencrypt:
      contactEmail: tony_cricelli@berkeley.edu
  service:
    loadBalancerIP: 35.223.10.143
prePuller:
  enabled: false
singleuser:
  image:
    name: montereytony/ugba147
    tag: ugba147-Spring-2021-7
  memory:
    limit: 4G
    guarantee: .5G
  cpu:
    limit: 4
    guarantee: 0.25
  storage:
    capacity: 50Gi
    dynamic:
      storageClass: standard
#      storageClass: jupyterhub-user-ssd
  lifecycleHooks:
    postStart:
      exec:
        command: ["/bin/sh", "-c", "/tmp/add_files.sh;gitpuller https://github.com/rahuntsinger/ugba147test main shared"]
auth:
  type: google
  google:
    clientId: "152813298217-1e7ap4ie9rugg5mfh2nmenc3f7d9o55g.apps.googleusercontent.com"
    clientSecret: "jXNHCWRcYWfXW1Y9HV0zhUuZ"
    callbackUrl: "https://ugba88.haastech.org/hub/oauth_callback"
    hostedDomain: [berkeley.edu]
    loginService: "your Berkeley Account."
  admin:
    users:
      - tony_cricelli
      - rhuntsinger
