scheduling:
  userScheduler:
    enabled: true
  podPriority:
    enabled: true
#  userPlaceholder:
#    enabled: true
#    replicas: 1
#  userPods:
#    nodeAffinity:
#      matchNodePurpose: require
cull:
  enabled: true
  timeout: 3600
  every: 300
hub:
  cookieSecret: "4488e38105f3a39166ed09d16616e34b9fc6443a175d5acca7b1dec4deb88d7e"
  db:
    type: sqlite-memory
proxy:
  secretToken: "0a1a4a1416042dd41917204450aa67abf37346e2629414ad12487352406d1295"
  https:
    enabled: true
    hosts:
      - mba290t-13.haastech.org
    letsencrypt:
      contactEmail: tony_cricelli@berkeley.edu
  service:
    loadBalancerIP: 34.136.255.218
prePuller:
  enabled: false
singleuser:
  image:
    name: montereytony/sql101
    tag: latest
    pullPolicy: IfNotPresent
  memory:
    limit: 2G
    guarantee: .5G
  cpu:
    limit: 1
    guarantee: .5
  storage:
    capacity: 1Gi
    dynamic:
      storageClass: standard
#  lifecycleHooks:
#    postStart:
#      exec:
#        command: ["/bin/sh", "-c", "/tmp/add_files.sh;mkdir -p my-work"]
  config:
    GoogleOAuthenticator:
      clientId: "152813298217-1e7ap4ie9rugg5mfh2nmenc3f7d9o55g.apps.googleusercontent.com"
      clientSecret: "jXNHCWRcYWfXW1Y9HV0zhUuZ"
      oauth_callback_url: "https://mba290t-13.haastech.org/hub/oauth_callback"
      hosted_domain: "berkeley.edu"
      login_service: "your Berkeley Account."
    JupyterHub:
      authenticator_class: google
    Authenticator:
      admin_users:
        - tony_cricelli
        - adelkar
