hub:
  cookieSecret: "8039bd67e969588a1f2479bc734f08ffa29cd1ba8e758a267ae494063d132b87"
  db:
    type: sqlite-memory
proxy:
  secretToken: "8528a6c22627c095f2ababf95becea1ca04454ebfdbd458341c5191d85c59f72"
  https:
    enabled: true
    hosts:
      - mba267-11.haastech.org
    letsencrypt:
      contactEmail: tony_cricelli@berkeley.edu
  service:
    loadBalancerIP: 35.239.142.133
prePuller:
  enabled: false
singleuser:
  image:
    name: montereytony/ugba147
    tag: tensorflow-Spring-2020
#    name: montereytony/mba263
#    tag: 103042
  memory:
    limit: 6G
    guarantee: 1G
  cpu:
    limit: 2
    guarantee: 1
  storage:
    capacity: 5Gi
    dynamic:
      storageClass: standard
#      storageClass: jupyterhub-user-ssd
  lifecycleHooks:
    postStart:
      exec:
        command:
          - "sh"
          - "-c"
          - >
            mkdir -p my-work
#            gitpuller https://github.com/rahuntsinger/ugba147test main shared
auth:
  type: google
  google:
    clientId: "152813298217-1e7ap4ie9rugg5mfh2nmenc3f7d9o55g.apps.googleusercontent.com"
    clientSecret: "jXNHCWRcYWfXW1Y9HV0zhUuZ"
    callbackUrl: "https://mba267-11.haastech.org/hub/oauth_callback"
    hostedDomain: [berkeley.edu]
    loginService: "your Berkeley Account."
