gcloud beta container     \
    --project "haas-jupyter-jub" clusters create "gke-2022-fall"     \
    --zone "us-central1-c"     \
    --no-enable-basic-auth     \
    --cluster-version "1.22.8-gke.202"     \
    --release-channel "regular"     \
    --machine-type "e2-medium"     \
    --image-type "COS_CONTAINERD"     \
    --disk-type "pd-standard"     \
    --disk-size "100"     \
    --metadata disable-legacy-endpoints=true     \
    --scopes "https://www.googleapis.com/auth/devstorage.read_only","https://www.googleapis.com/auth/logging.write","https://www.googleapis.com/auth/monitoring","https://www.googleapis.com/auth/servicecontrol","https://www.googleapis.com/auth/service.management.readonly","https://www.googleapis.com/auth/trace.append"     \
    --max-pods-per-node "110"     \
    --num-nodes "3"     \
    --logging=SYSTEM,WORKLOAD     \
    --monitoring=SYSTEM     \
    --enable-ip-alias     \
    --network "projects/haas-jupyter-jub/global/networks/default"     \
    --subnetwork "projects/haas-jupyter-jub/regions/us-central1/subnetworks/default"     \
    --no-enable-intra-node-visibility     \
    --default-max-pods-per-node "110"     \
    --no-enable-master-authorized-networks     \
    --addons HorizontalPodAutoscaling,HttpLoadBalancing,GcePersistentDiskCsiDriver     \
    --enable-autoupgrade     \
    --enable-autorepair     \
    --max-surge-upgrade 1     \
    --max-unavailable-upgrade 0     \
    --enable-shielded-nodes     \
    --node-locations "us-central1-c" &&     \
\
gcloud beta container     \
    --project "haas-jupyter-jub" node-pools create "pool-1"     \
    --cluster "gke-2022-fall"     \
    --zone "us-central1-c"     \
    --machine-type "n1-standard-2"    \
    --image-type "COS_CONTAINERD"     \
    --disk-type "pd-standard"     \
    --disk-size "100"     \
    --metadata disable-legacy-endpoints=true     \
    --scopes "https://www.googleapis.com/auth/devstorage.read_only","https://www.googleapis.com/auth/logging.write","https://www.googleapis.com/auth/monitoring","https://www.googleapis.com/auth/servicecontrol","https://www.googleapis.com/auth/service.management.readonly","https://www.googleapis.com/auth/trace.append"     \
    --enable-autoscaling     \
    --min-nodes "0"     \
    --max-nodes "10"     \
    --enable-autoupgrade     \
    --enable-autorepair     \
    --max-surge-upgrade 1     \
    --max-unavailable-upgrade 0     \
    --max-pods-per-node "110"     \
    --node-labels hub.jupyter.org/node-purpose=user \
    --node-taints hub.jupyter.org_dedicated=user:NoSchedule \
    --preemptible 
