#apiVersion: policy/v1
#scheduling:
# userScheduler:
#   enabled: true
# podPriority:
#   enabled: true
# userPlaceholder:
#   enabled: false
#   replicas: 2
#cull:
# enabled: false
# users: false
# timeout: 7200
# every: 1200
#prePuller:
#  hook:
#    enabled: false
#  continuous:
#    enabled: false
prePuller:
  resources:
    requests:
      cpu: 10m
      memory: 8Mi
  hook:
    resources:
      requests:
        cpu: 10m
        memory: 8Mi
singleuser:
  cloudMetadata:
    blockWithIptables: false
  extraEnv:
    EDITOR: "vim"
  image:
    name: montereytony/ugba-rah-sp22
    tag: jup2-02
  memory:
    limit: 2G
    guarantee: 1G
  cpu:
    limit: .50
    guarantee: .25
  storage:
    type: nfs-pv-ugba147-fall22-home
    extraVolumes:
      - name: persistent-storage
        persistentVolumeClaim:
          claimName: nfs-pv-ugba147-fall22-home
    extraVolumeMounts:
      - name: persistent-storage
        mountPath: '/home/jovyan'
        subPath: 'home/{username}'
# storage:
#   dynamic:
#     storageClass: nfs-pc
#   extraVolumes:
#     - name: jupyterhub-shared
#       persistentVolumeClaim:
#         claimName: nfs-pv-ugba147-fall22-shared
#   extraVolumeMounts:
#     - name: jupyterhub-shared
#       mountPath: /home/jovyan/shared
#       readOnly: true
# lifecycleHooks:
#   postStart:
#     exec:
#       command:
#         - "sh"
#         - "-c"
#         - >
#           mkdir -p my-work;
#           /bin/sh /tmp/add_files.sh;
proxy:
  secretToken: "f33560f2a799bf1431f96de9b40b9306b0a9d67568529909c8152cf871514f70"
  https:
    enabled: true
    hosts:
      - ugba147-2022-fall.haastech.org
    letsencrypt:
      contactEmail: tony_cricelli@berkeley.edu
  service:
    loadBalancerIP: 34.72.27.196
hub:
  cookieSecret: "4341d4ff03006d8f4efc7dcd2822a113772849327bceec4e313f341863af29fd"
  db:
    type: sqlite-memory
  config:
    GoogleOAuthenticator:
      client_id: 152813298217-1e7ap4ie9rugg5mfh2nmenc3f7d9o55g.apps.googleusercontent.com
      client_secret: jXNHCWRcYWfXW1Y9HV0zhUuZ
      oauth_callback_url: https://ugba147-2022-fall.haastech.org/hub/oauth_callback
      hosted_domain:
        - berkeley.edu
      login_service: your Berkeley Account.
    JupyterHub:
      authenticator_class: google
    Authenticator:
      admin_users:
        - tony_cricelli
        - rhuntsinger
        - rongsen_li
      allowed_users:
        - tony_cricelli
