hub:
  cookieSecret: "471e11a7477d228deb0834161b1416d44b5f1d72ced98b64e179092d1a1e484b"
  db:
    type: sqlite-memory
  concurrentSpawnLimit: 200
  extraConfig:
    announcements: |
      c.JupyterHub.template_vars.update({ 'announcement': 'Report issues to tony_cricelli@berkeley.edu', })
proxy:
  secretToken: "9478c1388c1cadc8aa48c074c21e9cdb85d3d12b8bb8128494145db91494ffa9"
  https:
    enabled: true
    hosts:
      - ugba147-2021-fall.haastech.org
    letsencrypt:
      contactEmail: tony_cricelli@berkeley.edu
  service:
    loadBalancerIP: 34.66.67.223
prePuller:
  enabled: false
singleuser:
  image:
    name: montereytony/ugba147
    tag: ugba88-Spring-2021-17
  memory:
    limit: 4G
    guarantee: .5G
  cpu:
    limit: 2
    guarantee: 0.25
  storage:
    type: "nfs"
    static:
      pvcName: "nfs-pv-ugba147-2021-fall-home"
      subPath: 'home/{username}'
#  storage:
#    extraVolumes:
#      - name: nfs-pv-ugba147-2021-fall-home
#        persistentVolumeClaim:
#          claimName: nfs-pv-ugba147-2021-fall-home
#    extraVolumeMounts:
#      - name: nfs-pv-ugba147-2021-fall-home
#        mountPath: /home/{username}
#        readOnly: false
#  defaultUrl: "/lab"
  lifecycleHooks:
    postStart:
      exec:
        command:
          - "sh"
          - "-c"
          - >
            export GIT_DISCOVERY_ACROSS_FILESYSTEM=1;
            mkdir -p my-work;
            bash /tmp/add_files.sh;
auth:
  type: google
  google:
    clientId: "152813298217-1e7ap4ie9rugg5mfh2nmenc3f7d9o55g.apps.googleusercontent.com"
    clientSecret: "jXNHCWRcYWfXW1Y9HV0zhUuZ"
    callbackUrl: "https://ugba147-2021-fall.haastech.org/hub/oauth_callback"
    hostedDomain: [berkeley.edu]
    loginService: "your Berkeley Account."
  admin:
    users:
      - tony_cricelli
      - rhuntsinger
      - omer_ardic
      - asantillan
  whitelist:
    users:
      - tony_cricelli
      - rhuntsinger
      - fox
      - suzanneharrison
