#https://www.linuxtechi.com/configure-nfs-persistent-volume-kubernetes/
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-ugba147-2021-fall-home
spec:
  capacity:
    storage: 500Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: nfs
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    server: 10.42.203.178
    path: /home
    readOnly: false
  accessModes:
  - ReadWriteMany
