hub:
  cookieSecret: "e7f8558dd307cbad56b5eb596e63190ae346500df33525ebe271cfa358c68214"
  db:
    type: sqlite-memory
proxy:
  secretToken: "06c5061f7e4244e3577079169c6991fe4ce0a014236b940c2861455e31c85e2b"
#  service:
#    type: ClusterIP
prePuller:
  enabled: false
singleuser:
  image:
    name: montereytony/rstudio
    tag: yuvidesktop7
#    name: montereytony/sql101
#    tag: latest
  memory:
    limit: 1G
    guarantee: .5G
  cpu:
    limit: 1
    guarantee: .5
  storage:
    capacity: 5Gi
    dynamic:
      storageClass: standard
#      storageClass: jupyterhub-user-ssd
  lifecycleHooks:
    postStart:
      exec:
        command:
          - "sh"
          - "-c"
          - >
            mkdir -p my-work
#            /opt/conda/bin/gitpuller https://github.com/rahuntsinger/ugba147test main shared;
auth:
  type: google
  google:
    clientId: "152813298217-1e7ap4ie9rugg5mfh2nmenc3f7d9o55g.apps.googleusercontent.com"
    clientSecret: "jXNHCWRcYWfXW1Y9HV0zhUuZ"
    callbackUrl: "https://pierre.haastech.org/hub/oauth_callback"
    hostedDomain: [berkeley.edu]
    loginService: "your Berkeley Account."
