apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-ugba147-fall22-home
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: nfs
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /home/ugba147/ugba147-2022-fall/home
    server: 10.128.0.10
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pv-ugba147-fall22-home
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
