apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jupyterhub-shared-volume
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi

#kind: StorageClass
#apiVersion: storage.k8s.io/v1
#metadata:
#  name: pd-standard
#provisioner: kubernetes.io/gce-pd
#parameters:
#  zones: us-central1-b



