#https://www.linuxtechi.com/configure-nfs-persistent-volume-kubernetes/
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-mfe230x-fall-2021
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: nfs
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /home/mfe230x/fall-2021
    server: 10.128.0.10
