#
# Build: docker build --rm --tag ds-test .
# Push: docker tag my_image $DOCKER_ID_USER/my_image
#
# git status
# git commit -m "comments Ubuntu and R to 3.4.2 "
# git push


FROM jupyter/datascience-notebook:latest
USER root
ENV DEBIAN_FRONTEND noninteractive

# Let's do updates first and install some needed libraries and utilites
RUN apt-get update && apt-get install -y --no-install-recommends apt-utils software-properties-common
RUN apt-get update -y  && apt-get dist-upgrade -y
RUN apt -y install build-essential libssl-dev libffi-dev python-dev  lib32ncurses5-dev zip  unzip libsuitesparse-dev 
# gtar was used by pandoc so we need this
RUN ln -s /bin/tar /bin/gtar
RUN apt-get remove r-base-core -y && apt-get install r-base-core -y
RUN conda install -c r r-igraph 

RUN conda install \
        ipython \
        numpy \
        fenics.2017\
        mshr \
        pandas \
    	plotnine \
    	matplotlib \
    	seaborn \
    	phantomjs  \
    	statsmodels \
    	statsmodels \
    	python-utils

RUN conda install -c https://conda.anaconda.org/amueller wordcloud

# NB extensions is not working when running it in jupyterhub kubernetes so adding this next line
#
RUN conda install -c conda-forge jupyter_contrib_nbextensions
RUN jupyter nbextension install --py widgetsnbextension --sys-prefix
RUN jupyter nbextension enable  --py widgetsnbextension --sys-prefix

RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y  software-properties-common && \
    add-apt-repository ppa:webupd8team/java -y && \
    apt-get update && \
    echo oracle-java7-installer shared/accepted-oracle-license-v1-1 select true | /usr/bin/debconf-set-selections && \
    apt-get install -y oracle-java8-installer && \
    apt-get clean \
    apt autoremove
#####Important########
##To set Oracle JDK8 as default, install the "oracle-java8-set-default" package.
##E.g.: sudo apt install oracle-java8-set-default
##On Ubuntu systems, oracle-java8-set-default is most probably installed
##automatically with this package.
######################

#RUN  apt install oracle-java8-set-default
#RUN export LD_LIBRARY_PATH=/usr/lib/jvm/java-8-oracle/jre/lib/amd64/server
#RUN Rscript -e "install.packages('https://cran.r-project.org/src/contrib/rJava_0.9-9.tar.gz',repos=NULL)"

RUN export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$JAVA_LD_LIBRARY_PATH
RUN R CMD javareconf
RUN Rscript -e "install.packages('https://cran.r-project.org/src/contrib/RWekajars_3.9.3-1.tar.gz',repos=NULL)"
#RUN conda install -c glaxosmithkline r-rwekajars 

#RUN Rscript -e "install.packages('https://cran.r-project.org/src/contrib/RWekajars_3.9.2-1.tar.gz',repos=NULL)"
#RUN Rscript -e "install.packages('https://cran.r-project.org/src/contrib/RWeka_0.4-37.tar.gz',repos=NULL)"
#RUN Rscript -e "install.packages('https://cran.r-project.org/src/contrib/rpart.plot_2.1.2.tar.gz',repos=NULL)"
#RUN Rscript -e "install.packages('https://cran.r-project.org/src/contrib/gbm_2.1.3.tar.gz',repos=NULL)"
ADD install_libraries.R /tmp
RUN R -f /tmp/install_libraries.R
#
# This should allow users to turn off extension if they do not want them.
#
USER jovyan
RUN jupyter nbextensions_configurator enable
