hub:
  cookieSecret: "4ebcd101be7f727dad910421e7847468cb1d7dd545f6f1d47f68aedc227372ef"
  db:
    type: sqlite-memory
proxy:
  secretToken: "29822718863bdb34a881e483fd57f9a8d95c067247e6ac72f876bf030e0aa1ca"
  https:
    enabled: true
    hosts:
      - ewmba263-2.haastech.org
    letsencrypt:
      contactEmail: tony_cricelli@berkeley.edu
  service:
    loadBalancerIP: 35.225.29.195
prePuller:
  enabled: false
singleuser:
  image:
     name: montereytony/mba263
     tag: 121419
  memory:
    limit: 2G
    guarantee: .5G
  cpu:
    limit: 1
    guarantee: 0.25
  storage:
    capacity: 10Gi
    dynamic:
      storageClass: standard
    extraVolumes:
      - name: jupyterhub-shared
        persistentVolumeClaim:
          claimName: nfs-pv-ewmba263-2
    extraVolumeMounts:
      - name: jupyterhub-shared
        mountPath: /home/jovyan/shared
  lifecycleHooks:
    postStart:
      exec:
        command: ["/bin/sh", "-c", "mkdir -p my-work"]
auth:
  type: google
  google:
    clientId: "152813298217-1e7ap4ie9rugg5mfh2nmenc3f7d9o55g.apps.googleusercontent.com"
    clientSecret: "jXNHCWRcYWfXW1Y9HV0zhUuZ"
    callbackUrl: "https://ewmba263-2.haastech.org/hub/oauth_callback"
    hostedDomain: [berkeley.edu]
    loginService: "your Berkeley Account."
  admin:
    users:
      - przemekj
      - tony_cricelli
