#
#
# Build: docker build --rm --tag montereytony/ugba147-2:ming .
# Push: docker tag my_image $DOCKER_ID_USER/my_image
#
#
FROM montereytony/ugba147
USER root
RUN ln -s /usr/lib/git-core/* /usr/local/bin
#RUN conda update -n base conda 
#RUN conda update conda 
#RUN sudo -H /opt/conda/bin/conda install python=3.6.3
#RUN sudo -H /opt/conda/bin/pip install --upgrade pip
RUN sudo -H /opt/conda/bin/pip install Cython --install-option="--no-cython-compile"
RUN sudo -H /opt/conda/bin/pip install --upgrade oauthenticator nbgitpuller nbinteract nbconvert six smart_open pymysql pandas isort autopep8 nltk numpy 
RUN sudo -H /opt/conda/bin/pip install --upgrade gensim pathos spacy flashtext setuptools  six setuptools_git
RUN sudo -H /opt/conda/bin/conda install -c conda-forge jupyter_contrib_nbextensions jupyter_nbextensions_configurator gensim

#RUN sudo -H /opt/conda/bin/conda update -n base conda
#RUN ENV DEBIAN_FRONTEND=noninteractive && 
RUN sudo -H apt-get -y install --upgrade python-wheel 
#RUN sudo -H /opt/conda/bin/pip install glove

# add glove-python
RUN cd /tmp && \
    git clone https://github.com/maciejkula/glove-python.git && \
    cd glove-python && \
    python setup.py install
#ADD glove /tmp/glove
#RUN cd /tmp/glove; make && make install
#RUN rm -r -f /tmp/glove;


#RUN sudo -H jupyter nbextension install --py widgetsnbextension --sys-prefix
#RUN sudo -H jupyter nbextension enable  --py widgetsnbextension --sys-prefix
#RUN sudo -H jupyter serverextension enable --sys-prefix      nbgitpuller nbinteract nbconvert
#RUN sudo -H jupyter nbextensions_configurator enable
#RUN sudo -H jupyter nbextension enable --py jupyter_contrib_nbextensions --sys-prefix
USER jovyan
