FROM jupyter/datascience-notebook:latest
USER root
ENV DEBIAN_FRONTEND noninteractive
ENV PATH=/opt/conda/bin:$PATH
ENV export PREFIX=/opt/conda

# Updating Ubuntu packages
RUN apt-get update --fix-missing && yes|apt-get upgrade
RUN apt-get update -y --fix-missing  && apt-get dist-upgrade -y
RUN apt-get update -y  && apt-get upgrade -y

#Update again
RUN apt-get update && apt-get install -y --no-install-recommends apt-utils software-properties-common
RUN apt -y install build-essential libssl-dev libffi-dev lib32ncurses5-dev zip  unzip libsuitesparse-dev python3-dev python3-pip wget bzip2 curl
RUN /opt/conda/bin/pip install --upgrade pip
RUN curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py && /opt/conda/bin/python get-pip.py

# gtar was used by pandoc so we need this
RUN ln -s /bin/tar /bin/gtar

