singleuser:
  cloudMetadata:
    blockWithIptables: false
  image:
    name: montereytony/ugba-rah-sp22
    tag: jup2-02
  memory:
    limit: 1G
    guarantee: .5G
  cpu:
    limit: .5
    guarantee: .25
prePuller:
  hook:
    enabled: false
proxy:
  secretToken: "01010101a799bf1431f96de9b40b9306b0a9d67568529909c8152cf871514f70"
hub:
  cookieSecret: "0101010103006d8f4efc7dcd2822a113772849327bceec4e313f341863af29fd"
  db:
    type: sqlite-memory
  config:
    DummyAuthenticator:
      password: N@choY0Mama
    JupyterHub:
      authenticator_class: dummy
    Authenticator:
      admin_users:
        - tony
      allowed_users:
        - yoshi
        - zane
        - pchew
