apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
  labels:
    2022: fall
spec:
  capacity:
    storage: 123Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /home/ugba147/ugba147-2022-fall/shared
    server: 10.128.0.10
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nfs-pv
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  selector:
    matchLabels:
      2022: fall
  resources:
    requests:
      storage: 11Gi
