apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pv-ugba147-fall22-shared
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
